<!-- 
This is a copy of a file managed by the Web Team, not part of our code.
It's only for dev and sre and is not to be included in a real deployment.
-->

<div id="handy">

<div id="sidebarlinks">

<div class="block">

<h2>Handy links</h2>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/starting-your-job-search.html" target="_blank">Starting your job search</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/cvs-and-covering-letters.html" target="_blank">Writing your CV and covering letters</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/where-to-look.html" target="_blank">Where to look</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/job-leads.html" target="_blank">Finding job leads</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/applying-for-jobs-tips.html" target="_blank">Appling for a job</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/job-interview.html" target="_blank">Job interviews</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/get-the-job.html" target="_blank">When you get the job</a></div>

<div class="links website"><a href="http://jobs.nzherald.co.nz/" target="_blank">jobs.nzherald.co.nz</a></div>

<div class="links website"><a href="http://www.jobs.co.nz/" target="_blank">www.jobs.co.nz</a></div>

<div class="links website"><a href="http://www.bestjobs.co.nz/" target="_blank">www.bestjobs.co.nz</a></div>

<div class="links website"><a href="https://jobs.govt.nz/" target="_blank">jobs.govt.nz</a></div>

<div class="links website"><a href="http://careers.msd.govt.nz/login.aspx?coid=210" target="_blank">MSD Careers</a></div>

<div class="links website"><a href="http://www.greensky.co.nz/" target="_blank">Green Sky - Hire &amp; Be Hired Directly</a></div>

<div class="links website"><a href="http://www.sjs.co.nz/search/jobs" target="_blank">Student Job Search</a></div>

<div class="links website"><a href="http://nz.indeed.com/" target="_blank">Indeed.com</a></div>

<div class="links website"><a href="http://myjobspace.co.nz/" target="_blank">myjobspace.co.nz</a></div>

<div class="links website"><a href="http://www.hospotrade.co.nz/Jobs" target="_blank">Hospotrade - Hospitality jobs</a></div>

</div><!-- End block -->
</div><!-- End sidebarlinks -->
</div><!-- End handy -->