allareas = [
"Abbotsford",
"Abel Tasman National Park",
"Acacia Bay",
"Acton",
"Adair",
"Admiral Hill",
"Admiralty Bay",
"Ahaura",
"Ahiaruhe",
"Ahikouka",
"Ahipara",
"Ahititi",
"Ahuriri Conservation Park",
"Ahuriri Flat",
"Airedale",
"Aka Aka",
"Akaroa",
"Akatarawa",
"Akatarawa Valley",
"Akatore",
"Akitio",
"Albany",
"Albany Heights",
"Albert Town",
"Albury",
"Alexandra",
"Alford Forest",
"Alfredton",
"Alfriston",
"Algies Bay",
"Allandale",
"Allanton",
"Allenton",
"Alma",
"Alton",
"Amberley",
"Amodeo Bay",
"Amuri Plain",
"Anakiwa",
"Anakoha",
"Anawhata",
"Anderson Park",
"Aniseed Valley",
"Aokautere",
"Aongatete",
"Aorangi",
"Aorangi Forest Park",
"Aotuhia",
"Aparima",
"Apiti",
"Appleby",
"Arahura Valley",
"Aramoana",
"Aranga",
"Arapohue",
"Arapuni",
"Ararata",
"Ararimu",
"Ararua",
"Aratapu",
"Ardlussa",
"Ardmore",
"Argyle Corner",
"Argyle Hill",
"Argyll",
"Aria",
"Arnold Valley",
"Arrow Junction",
"Arrowtown",
"Arthurs Pass",
"Arthurs Pass National Park",
"Arthurs Point",
"Arundel",
"Ashburton",
"Ashburton Forks",
"Ashburton Lakes",
"Ashers",
"Ashhurst",
"Ashley",
"Ashley Clinton",
"Ashley Downs",
"Ashley Forest",
"Ashton",
"Ashwick Flat",
"Ataahua",
"Atapo",
"Atarau",
"Athenree",
"Athenree Gorge",
"Athol",
"Atiamuri",
"Auckland",
"Aukopae",
"Auroa",
"Aviemore",
"Awahuri",
"Awaiti",
"Awakeri",
"Awakino",
"Awakino Point",
"Awamangu",
"Awamoa",
"Awamoko",
"Awanui",
"Awapuni",
"Awaroa",
"Awaroa Bay",
"Awarua",
"Awarua Plains",
"Awarua Wetlands",
"Awatere",
"Awatere Valley",
"Awatoto",
"Awatuna",
"Awhitu",
"Bainham",
"Balcairn",
"Balclutha",
"Bald Hill",
"Balfour",
"Ballance",
"Balmoral",
"Bankside",
"Bannockburn",
"Barnhill",
"Barrhill",
"Barrytown",
"Bay View",
"Baylys Beach",
"Bayswater",
"Beachlands",
"Beaconsfield",
"Beatrix Bay",
"Beaumont",
"Becks",
"Belfast",
"Belfield",
"Belgrove",
"Bell Block",
"Bell Island",
"Belmont",
"Ben Lomond",
"Ben Ohau",
"Ben Omar",
"Bendigo",
"Benhar",
"Benmore",
"Benneydale",
"Berwick",
"Berwick Forest",
"Best Island",
"Bethells Beach",
"Bideford",
"Bidwells Cutting",
"Big Omaha",
"Birchwood",
"Bird Road",
"Birdlings Flat",
"Birdwood",
"Black Point",
"Black Rock",
"Blackball",
"Blackhead",
"Blackmans",
"Blackmount",
"Blairlogie",
"Blenheim",
"Blind River",
"Blue Lakes",
"Blue Mountains",
"Blue Spur",
"Bluff",
"Bluff Hill",
"Bombay",
"Bottle Lake",
"Bowentown",
"Braeburn Range",
"Branxholme",
"Braxton",
"Bridge Pa",
"Brighton",
"Brightwater",
"Brixton",
"Broadlands",
"Broadlands Forest",
"Broadwood",
"Bronte",
"Brookby",
"Brooklands",
"Brooklyn",
"Broomfield",
"Broughton Bay",
"Browns",
"Bruce Bay",
"Brunswick",
"Brydone",
"Brynderwyn",
"Buckland",
"Bucklands Crossing",
"Bulls",
"Bulwer",
"Bunnythorpe",
"Burbush",
"Burgess Park",
"Burkes Pass",
"Burleigh",
"Burnham",
"Burnt Hill",
"Bushey",
"Butchers Gully",
"Caberfeidh",
"Cable Bay",
"Camborne",
"Cambrians",
"Cambridge",
"Camerons",
"Canvastown",
"Cape Foulwind",
"Cape Palliser",
"Cape Reinga",
"Cape Runaway",
"Cape Saunders",
"Cardiff",
"Cardrona",
"Carew",
"Careys Bay",
"Caroline",
"Carrington",
"Carters Beach",
"Carterton",
"Cashmere",
"Cass Bay",
"Castle Downs",
"Castle Hill",
"Castlepoint",
"Castlerock",
"Catlins Forest Park",
"Cattle Creek",
"Cattle Flat",
"Cave",
"Cavendish",
"Centre Bush",
"Centre Hill",
"Chain Hills",
"Charing Cross",
"Charleston",
"Charlton",
"Charteris Bay",
"Chaslands",
"Chatham Islands",
"Chatto Creek",
"Chatton",
"Chatton North",
"Cheltenham",
"Chertsey",
"Cheviot",
"Christchurch",
"Churchill",
"Churton Park",
"Circle Hill",
"Cissy Bay",
"Clandeboye",
"Claremont",
"Clarence",
"Clarendon",
"Clareville",
"Clarks Beach",
"Clarks Junction",
"Clarkville",
"Clevedon",
"Clifden",
"Clifton",
"Clinton",
"Clive",
"Closeburn",
"Cloverlea",
"Clyde",
"Clydevale",
"Coal Creek",
"Coal Creek Flat",
"Coal Stream",
"Coalgate",
"Coastlands",
"Coatesville",
"Colac Bay",
"Coldstream",
"Collingwood",
"Colville",
"Colyton",
"Conical Hill",
"Conroys Gully",
"Conway Flat",
"Cooks Beach",
"Coopers Beach",
"Coopers Creek",
"Cormacks",
"Cornish Point",
"Cornwallis",
"Coroglen",
"Coromandel",
"Coromandel Forest Park",
"Coronet Peak",
"Corriedale",
"Corsair Bay",
"Corstorphine",
"Coutts Island",
"Cracroft",
"Craigellachie",
"Craigieburn Forest Park",
"Craigs Flat",
"Crail Bay",
"Crichton",
"Crofton",
"Crofton Downs",
"Cromwell",
"Cromwell Gorge",
"Crookston",
"Crossans Corner",
"Crownthorpe",
"Croydon",
"Croydon Bush",
"Culverden",
"Curio Bay",
"Cust",
"Dacre",
"Dairy Flat",
"Dalefield",
"Dannevirke",
"Danseys Pass",
"Darfield",
"Dargaville",
"Dartmoor",
"Dean",
"Deborah",
"Deborah Bay",
"Delaware Bay",
"Denniston",
"Diamond Harbour",
"Diamond Peak",
"Dillmanstown",
"Dingle Burn",
"Dipton",
"Dipton West",
"Dobson",
"Dome Forest",
"Dome Valley",
"Domett",
"Donnellys Crossing",
"Dorie",
"Double Hill",
"Douglas",
"Dovedale",
"Doyleston",
"Dromore",
"Drummond",
"Drury",
"Drybread",
"Duck Creek",
"Dumbarton",
"Dunback",
"Dunearn",
"Dunedin",
"Dunganville",
"Dunrobin",
"Dunsandel",
"Dunsdale",
"Duntroon",
"Duvauchelle",
"Dyerville",
"Ealing",
"Earnscleugh",
"Earthquakes",
"East Cape",
"East Chatton",
"East Taieri",
"East Takaka",
"East Tamaki",
"East Taratahi",
"Eastbourne",
"Eastern Bush",
"Edendale",
"Edgecumbe",
"Edievale",
"Egmont National Park",
"Egmont Village",
"Eiffelton",
"Eighty Eight Valley",
"Eketahuna",
"Elaine Bay",
"Elderslie",
"Elephant Hill",
"Elgin",
"Elsthorpe",
"Eltham",
"Emu Plain",
"Enfield",
"Ermedale",
"Erua",
"Eskdale",
"Ettrick",
"Eureka",
"Evans Flat",
"Evansdale",
"Everett Park",
"Eyrewell Forest",
"Fairfax",
"Fairfield",
"Fairhall",
"Fairlie",
"Fairlight",
"Fairton",
"Fairview",
"Fairview Heights",
"Featherston",
"Feilding",
"Feldwick",
"Ferndale",
"Fernhill",
"Ferniehurst",
"Fernside",
"Finegand",
"Fiordland National Park",
"Fitzroy Bay",
"Five Forks",
"Five Roads",
"Flag Swamp",
"Flagstaff",
"Flat Bush",
"Flat Point",
"Flaxmere",
"Flaxton",
"Flemington",
"Fletcher Bay",
"Flints Bush",
"Fordell",
"Forsyth",
"Fortification",
"Fortrose",
"Fox Glacier",
"Fox River",
"Foxhill",
"Foxton",
"Foxton Beach",
"Frankton",
"Franz Josef Glacier",
"Franz Josef Glacier/Waiau",
"Fraser Dam",
"Frasertown",
"French Farm",
"French Pass",
"Freshford",
"Frimley",
"Fruitlands",
"Fuchsia Creek",
"Gabriels Gully",
"Galatea",
"Galloway",
"Garston",
"Gebbies Valley",
"Georgetown",
"Geraldine",
"Geraldine Downs",
"Geraldine Flat",
"Gibbston",
"Gimmerburn",
"Gisborne",
"Gladfield",
"Gladstone",
"Glasnevin",
"Glen Afton",
"Glen Avon",
"Glen Massey",
"Glen Murray",
"Glen Oroua",
"Glenavy",
"Glenbervie",
"Glenbrook",
"Glenbrook Beach",
"Glenburn",
"Glencoe",
"Glendhu Bay",
"Glenduan",
"Glengarry",
"Glenham",
"Glenhope",
"Gleniti",
"Glenkenich",
"Glenledi",
"Glenomaru Valley",
"Glenorchy",
"Glenore",
"Glenpark",
"Glentui",
"Glentunnel",
"Glenure",
"Glorit",
"Goat Island / Rakiriri",
"Golden Downs",
"Goodwood",
"Goose Bay",
"Gordon",
"Gordonton",
"Gore",
"Gore Bay",
"Gorge Road",
"Goughs Bay",
"Goulter Bay",
"Governors Bay",
"Gowan Hill",
"Gowanbridge",
"Grandview Heights",
"Granity",
"Great Barrier Island",
"Green Valley",
"Greendale",
"Greenfield",
"Greenhills",
"Greenhithe",
"Greenpoint",
"Greenstone",
"Greenstreet",
"Greenvale",
"Grenada North",
"Greta Valley",
"Greymouth",
"Greytown",
"Gropers Bush",
"Grove Burn",
"Grove Bush",
"Grovetown",
"Gummies Bush",
"Haast",
"Hadlow",
"Hahei",
"Hakaru",
"Hakataramea",
"Hakataramea Valley",
"Halcombe",
"Haldane",
"Half Moon Bay",
"Halfmoon Bay",
"Halswell",
"Hamilton",
"Hamilton Burn",
"Hampden",
"Hampton Downs",
"Hamurana",
"Hangatiki",
"Hanmer Forest",
"Hanmer Plain",
"Hanmer Springs",
"Happy Valley",
"Hapuku",
"Harewood",
"Harihari",
"Harington Point",
"Haruru",
"Harwood",
"Hastings",
"Hatepe",
"Hatfield",
"Hatuma",
"Haumoana",
"Haupiri",
"Hautapu",
"Hautere",
"Hauturu",
"Havelock",
"Havelock North",
"Hawai",
"Hawarden",
"Hawea",
"Hawea Flat",
"Hawera",
"Hawkesbury",
"Hawkswood",
"Hazelburn",
"Hazletts",
"Hector",
"Heddon Bush",
"Hedgehope",
"Helena Bay",
"Helensville",
"Henderson",
"Henderson Valley",
"Henley",
"Herbert",
"Herbertville",
"Herekino",
"Herekino Forest",
"Heriot",
"Hexton",
"Heyward Point",
"Hickory Bay",
"Hicks Bay",
"Highbank",
"Highcliff",
"Hihi",
"Hikuai",
"Hikumutu",
"Hikurangi",
"Hikutaia",
"Hilderthorpe",
"Hillend",
"Hillgrove",
"Hills Creek",
"Hillsborough",
"Hillside",
"Hilton",
"Himatangi",
"Himatangi Beach",
"Hinahina",
"Hinakura",
"Hindon",
"Hinds",
"Hira",
"Hoanga",
"Hochstetter",
"Hoe-O-Tainui",
"Hohonu",
"Hokio Beach",
"Hokitika",
"Hokonui",
"Hokonui Hills",
"Homebush",
"Homewood",
"Honikiwi",
"Hope",
"Hopkins Valley",
"Horeke",
"Hornby",
"Horohoro",
"Horokiwi",
"Horopito",
"Hororata",
"Horotiu",
"Horsham Downs",
"Hospital Hill",
"Hot Water Beach",
"Houhora",
"Howard",
"Howick",
"Huapai",
"Huia",
"Huinga",
"Huirangi",
"Huiroa",
"Hukerenui",
"Hundalee",
"Hunter",
"Hunter Valley",
"Hunters Hills",
"Hunterville",
"Huntingdon",
"Huntington",
"Huntly",
"Hunua",
"Hurford",
"Hurleyville",
"Hurunui",
"Hurworth",
"Hyde",
"Ida Valley",
"Idaburn",
"Ihuraua",
"Ikamatua",
"Ikawai",
"Inangahua",
"Inch Clutha",
"Inch Valley",
"Inchbonnie",
"Incholme",
"Inglewood",
"Inland Road",
"Invercargill",
"Invercargill Airport",
"Irthing",
"Isla Bank",
"Island Block",
"Island Cliff",
"Island Harbour",
"Island Hills",
"Island Stream",
"Islington",
"Iwitahi",
"Jackett Island",
"Jackson Bay",
"Jacksons",
"Jamestown",
"Johnsonville",
"Johnston",
"Josephville",
"Judgeford",
"Kaeo",
"Kahuranaki",
"Kahurangi National Park",
"Kahutara",
"Kai Iwi",
"Kai Iwi Beach",
"Kaiapoi",
"Kaiata",
"Kaiaua",
"Kaihere",
"Kaihiku",
"Kaihu",
"Kaikohe",
"Kaikoura",
"Kaikoura Flat",
"Kaimanawa Forest Park",
"Kaimarama",
"Kaimata",
"Kaimaumau",
"Kaimiro",
"Kainga",
"Kaingaroa",
"Kaingaroa Forest",
"Kaipara Flats",
"Kairakau",
"Kairanga",
"Kairua",
"Kaitaia",
"Kaitake",
"Kaitangata",
"Kaitawa",
"Kaiteriteri",
"Kaitieke",
"Kaitoke",
"Kaituna",
"Kaiuma Bay",
"Kaiwaka",
"Kaiwera",
"Kaiwhaiki",
"Kaiwhata",
"Kaka Point",
"Kakahi",
"Kakahu",
"Kakanui",
"Kakapotahi",
"Kakapuaka",
"Kakaramea",
"Kakatahi",
"Kamahi",
"Kamo",
"Kaniere",
"Kapenga",
"Kaponga",
"Kapuka",
"Kapuka South",
"Kapuni",
"Karaka",
"Karamea",
"Karamu",
"Karangahake",
"Karangarua",
"Karapiro",
"Karekare",
"Karetu",
"Karikari Peninsula",
"Karioitahi",
"Karitane",
"Karori",
"Katea",
"Katikati",
"Kauana",
"Kaukapakapa",
"Kaupokonui",
"Kauri",
"Kauru Hill",
"Kawakawa",
"Kawakawa Bay",
"Kawarau Falls",
"Kawarau Gorge",
"Kawau Island",
"Kaweka Forest Park",
"Kawerau",
"Kawhia",
"Kekerengu",
"Kelso",
"Kelvin Grove",
"Kenepuru Head",
"Kennedy Bay",
"Kennedys Bush",
"Kennington",
"Kerepehi",
"Kereru",
"Kereta",
"Kerikeri",
"Kerrytown",
"Kia Ora",
"Kihikihi",
"Kikiwa",
"Kimbell",
"Kimbolton",
"Kingseat",
"Kingston",
"Kingston Crossing",
"Kinleith",
"Kinleith Forest",
"Kinloch",
"Kinmont Park",
"Kiore",
"Kirikau",
"Kiripaka",
"Kiriwhakapapa",
"Kirkliston",
"Kirwee",
"Kiwitea",
"Knapdale",
"Knobby Range",
"Kohatu",
"Kohukohu",
"Kohuratahi",
"Koitiata",
"Kokatahi",
"Kokoamo",
"Kokonga",
"Kokopu",
"Kokotau",
"Komata",
"Kononi",
"Kopaki",
"Kopu",
"Kopuaranga",
"Kopuku",
"Koputaroa",
"Korito",
"Koromiko",
"Koru",
"Kotemaori",
"Kourarau Hill",
"Kuaotunu",
"Kumara",
"Kumara Junction",
"Kumeroa",
"Kumeu",
"Kuratau",
"Kuri Bush",
"Kuriwao",
"Kurow",
"Kutarere",
"Kyeburn",
"Kyeburn Diggings",
"Lagmhor",
"Laingholm",
"Lake Alice",
"Lake Coleridge",
"Lake Evelyn",
"Lake Ferry",
"Lake Georgina",
"Lake Grassmere",
"Lake Hawea",
"Lake Hayes",
"Lake Hayes Estate",
"Lake Matahina",
"Lake Ohakuri",
"Lake Ohia",
"Lake Okareka",
"Lake Okataina",
"Lake Onslow",
"Lake Pearson",
"Lake Pukaki",
"Lake Puketi",
"Lake Reserve",
"Lake Rotoma",
"Lake Roxburgh Village",
"Lake Selfe",
"Lake Sumner National Park",
"Lake Tarawera",
"Lake Taupo",
"Lake Tekapo",
"Langs Beach",
"Lansdowne",
"Larnachs Castle",
"Larrys Creek",
"Lauder",
"Lauriston",
"Lawrence",
"Le Bons Bay",
"Leamington",
"Lee Flat",
"Lee Stream",
"Lee Valley",
"Lees Valley",
"Leeston",
"Leigh",
"Leith Valley",
"Leithen Bush",
"Leithfield",
"Leithfield Beach",
"Lepperton",
"Leslie Hills",
"Letts Gully",
"Levels",
"Levels Valley",
"Levin",
"Lichfield",
"Lillburn",
"Limehills",
"Lincoln",
"Lindis Pass",
"Lindis Valley",
"Linkwater",
"Lintley",
"Linton",
"Linton Camp",
"Linwood",
"Lismore",
"Little Akaloa",
"Little River",
"Little Valley",
"Little Wanganui",
"Livingstone",
"Loburn",
"Lochiel",
"Lochindorb",
"Long Bay",
"Longburn",
"Longbush",
"Longford",
"Longlands",
"Longridge",
"Longridge North",
"Longwood",
"Lorneville",
"Lovells Flat",
"Lowburn",
"Lowcliffe",
"Lower Dashwood",
"Lower Hutt",
"Lower Kaimai",
"Lower Moutere",
"Lower Nevis",
"Lower Portobello",
"Lower Shotover",
"Lowry Hills Range",
"Lowther",
"Lucas Heights",
"Luggate",
"Lumsden",
"Lyford",
"Lyttelton",
"Maata",
"Mabel Bush",
"Macdonald Downs",
"Maclennan",
"Macraes Flat",
"Maerewhenua",
"Mahana",
"Maharahara",
"Mahau Sound",
"Maheno",
"Mahia",
"Mahia Beach",
"Mahoe",
"Mahoenui",
"Mahurangi East",
"Mahurangi West",
"Mahuta",
"Maihiihi",
"Mairehau",
"Maitai",
"Maitland",
"Makahu",
"Makakahi",
"Makara",
"Makara Beach",
"Makaraka",
"Makarau",
"Makareao",
"Makarewa",
"Makarora",
"Maketu",
"Makikihi",
"Makomako",
"Makuri",
"Malvern Hills",
"Mamaku",
"Mamaranui",
"Manaia",
"Manakau",
"Manapouri",
"Manaroa",
"Manawahe",
"Manawaru",
"Mandeville",
"Mangakino",
"Mangakura",
"Mangamahu",
"Mangamaunu",
"Mangamingi",
"Mangamuka",
"Mangamutu",
"Mangaokewa",
"Mangaorapa",
"Mangaotaki",
"Mangapai",
"Mangapakeha",
"Mangarakau",
"Mangaroa",
"Mangatainoka",
"Mangatangi",
"Mangatarata",
"Mangatawhiri",
"Mangateparu",
"Mangateretere",
"Mangatoki",
"Mangaweka",
"Mangawhai",
"Mangawhai Heads",
"Mangawhai Point",
"Mangawhio",
"Mangles Valley",
"Mangonui",
"Mangorei",
"Manorburn",
"Manuka Creek",
"Manukau",
"Manukau Heads",
"Manunui",
"Manurewa",
"Manutahi",
"Manutuke",
"Mapua",
"Maraekakaho",
"Maraetai",
"Maraetotara",
"Marahau",
"Maramarua",
"Maramarua Forest",
"Mareretu",
"Marokopa",
"Maromaku",
"Maronan",
"Marotiri",
"Marsden",
"Marsden Point",
"Marshland",
"Martinborough",
"Marton",
"Maruia",
"Marybank",
"Masons Flat",
"Massey",
"Massey University",
"Masterton",
"Mata",
"Matahi",
"Matahina Forest",
"Matahiwi",
"Mataikona",
"Matakana",
"Matakana Island",
"Matakanui",
"Matakitaki",
"Matakohe",
"Matamata",
"Matamau",
"Matangi",
"Matapihi",
"Matapouri",
"Matapu",
"Matarangi",
"Matarau",
"Matata",
"Matatoki",
"Matau",
"Mataura",
"Mataura Island",
"Matauri Bay",
"Matawai",
"Matawaia",
"Matemateaonga",
"Matiere",
"Matira",
"Matiri",
"Matokitoki",
"Mauku",
"Maungakaramea",
"Maungakotukutuku",
"Maunganamu",
"Maungatapere",
"Maungatautari",
"Maungati",
"Maungaturoto",
"Maunu",
"Mauriceville",
"Mavora",
"Mawheraiti",
"Maxwell",
"Mayfield",
"Maymorn",
"Mcewens Bush",
"Mcleans Island",
"Mcnab",
"Meadowbank",
"Medbury",
"Meeanee",
"Menzies Ferry",
"Mercer",
"Meremere",
"Merino Downs",
"Merrivale",
"Merton",
"Mesopotamia",
"Methven",
"Mid Dome",
"Middle Valley",
"Middlemarch",
"Midhirst",
"Mihi",
"Mihiwaka",
"Mikimiki",
"Milburn",
"Milford",
"Milford Sound",
"Mill Road",
"Millers Flat",
"Millerton",
"Milson",
"Milton",
"Mimi",
"Mimihau",
"Minginui",
"Miranda",
"Mitcham",
"Mitimiti",
"Moa Creek",
"Moa Flat",
"Moana",
"Moawhango",
"Moeraki",
"Moerewa",
"Moetapu Bay",
"Mohakatino",
"Mokai",
"Mokau",
"Mokihinui",
"Mokoia",
"Mokoreta",
"Mokotua",
"Momona",
"Momorangi Bay",
"Monowai",
"Montalto",
"Moonlight",
"Moonshine Valley",
"Morere",
"Morrinsville",
"Morrisons",
"Morrisons Bush",
"Morton Mains",
"Morven",
"Mosgiel",
"Mossburn",
"Motatau",
"Motu",
"Motu Rimu",
"Motueka",
"Motueka Valley",
"Motukarara",
"Motumaoho",
"Motunau",
"Motunau Beach",
"Motunui",
"Motuoapa",
"Motupiko",
"Motupipi",
"Motutere",
"Mount Ajax",
"Mount Allan",
"Mount Aspiring",
"Mount Aspiring National Park",
"Mount Barker",
"Mount Bruce",
"Mount Cargill",
"Mount Cook",
"Mount Cook National Park",
"Mount Creighton",
"Mount Culverden",
"Mount Grand",
"Mount Hamilton",
"Mount Holdsworth",
"Mount Hutt",
"Mount Linton",
"Mount Maunganui",
"Mount Nicholas",
"Mount Peel",
"Mount Pisa",
"Mount Pleasant",
"Mount Prospect",
"Mount Richmond Forest Park",
"Mount Ruapehu",
"Mount Somers",
"Mount Stalker",
"Mount Stoker",
"Mount Tarawera",
"Mount Trotter",
"Mourea",
"Moutoa",
"Muhunoa East",
"Murchison",
"Muriwai",
"Muriwai Beach",
"Murupara",
"Myross Bush",
"Naike",
"Napier",
"Napier South",
"Naseby",
"National Park",
"Nelson",
"Nelson Lakes National Park",
"Nenthorn",
"Ness Valley",
"Netherby",
"Netherton",
"Nevis",
"New Haven",
"New Lynn",
"New Plymouth",
"New Plymouth Airport",
"New River Ferry",
"Newall",
"Newbury",
"Newland",
"Newstead",
"Ngaere",
"Ngahape",
"Ngahere",
"Ngahinapouri",
"Ngakuru",
"Ngakuta Bay",
"Ngamahanga",
"Ngamatapouri",
"Ngapara",
"Ngapuke",
"Ngapuna",
"Ngararatunua",
"Ngarua",
"Ngaruawahia",
"Ngataki",
"Ngatapa",
"Ngatea",
"Ngatimoti",
"Ngatira",
"Ngaumu",
"Ngawaro",
"Ngawha Springs",
"Ngongotaha",
"Ngongotaha Valley",
"Ngunguru",
"Niagara",
"Nightcaps",
"Nihotupu",
"Nikau Valley",
"Nine Mile",
"Nokomai",
"Nopera",
"Norfolk",
"Normanby",
"Norsewood",
"North Bank",
"North Harbour",
"North Shore",
"North Shore City",
"North Taieri",
"Northburn",
"Northope",
"Northwood",
"Nuhaka",
"Nukuhau",
"Nukuhou",
"Nukutawhiti",
"Oakleigh",
"Oakura",
"Oamaru",
"Oamaru North",
"Oaonui",
"Oaro",
"Ocean Beach",
"Ocean View",
"Oceanic",
"Ohaaki",
"Ohaeawai",
"Ohai",
"Ohakana Island",
"Ohakea",
"Ohakune",
"Ohakuri",
"Ohangai",
"Ohariu",
"Ohau",
"Ohauiti",
"Ohauparuparu Bay",
"Ohaupo",
"Ohawe",
"Ohinewai",
"Ohingaiti",
"Ohoka",
"Ohope",
"Ohuka",
"Ohura",
"Okaiawa",
"Okaihau",
"Okains Bay",
"Okaramio",
"Okarito",
"Okato",
"Okauia",
"Okere Falls",
"Okia Flat",
"Okiato",
"Okitu",
"Okiwi Bay",
"Okoia",
"Okoki",
"Okoroire",
"Okuku",
"Okuku Range",
"Okura",
"Okuti Valley",
"Omaha",
"Omahu",
"Omaio",
"Omakau",
"Omakere",
"Omamari",
"Omana",
"Omana Beach",
"Omanaia",
"Omanawa",
"Omapere",
"Omarama",
"Omata",
"Omataroa",
"Omaui",
"Omiha",
"Omihi",
"Omimi",
"Omokoroa",
"Omokoroa Beach",
"Omori",
"Onaero",
"Onahau Bay",
"Onamalutu",
"One Tree Point",
"Onekaka",
"Onemana",
"Onerahi",
"Oneroa",
"Onetangi",
"Onewhero",
"Ongaonga",
"Ongarue",
"Opaheke",
"Opaki",
"Oparau",
"Ophir",
"Opiki",
"Opio",
"Opito Bay",
"Opononi",
"Oporo",
"Opotiki",
"Opoutere",
"Opua",
"Opuawhanga",
"Opunake",
"Orangapai",
"Orari",
"Orari Bridge",
"Orari Gorge",
"Oratia",
"Orautoha",
"Orawia",
"Orepuki",
"Orere Point",
"Oreti Beach",
"Oreti Plains",
"Orewa",
"Orini",
"Ormond",
"Ormondville",
"Oromahoe",
"Orongo",
"Oropi",
"Orton",
"Oruanui",
"Oruawharo",
"Osborne",
"Ostend",
"Otahome",
"Otahu Flat",
"Otahuti",
"Otaihanga",
"Otaika",
"Otaio",
"Otaitai Bush",
"Otakeho",
"Otaki",
"Otaki Beach",
"Otakiri",
"Otakou",
"Otama",
"Otamauri",
"Otamita",
"Otane",
"Otangiwai",
"Otanomomo",
"Otapaurau",
"Otapiri",
"Otapiri Gorge",
"Otara",
"Otaraia",
"Otatara",
"Otaua",
"Otautau",
"Otekaieke",
"Otematata",
"Oteramika",
"Otewa",
"Otiake",
"Otipua Creek",
"Otira",
"Otorohanga",
"Otukou",
"Oturehua",
"Otway",
"Oue",
"Oueroa",
"Outram",
"Owaka",
"Owaka Valley",
"Oware",
"Owen River",
"Owhango",
"Owhata",
"Owhiro",
"Oxford",
"Paekakariki",
"Paengaroa",
"Paerata",
"Paerau",
"Paeroa",
"Paewhenua Island",
"Pahi",
"Pahia",
"Pahiatua",
"Paihia",
"Pakaraka",
"Pakawau",
"Pakipaki",
"Pakiri",
"Pakotai",
"Pakowhai",
"Pakuratahi",
"Palmerston",
"Palmerston North",
"Panguru",
"Papaiti",
"Papakaio",
"Papakura",
"Papamoa",
"Papamoa Beach",
"Papanui Junction",
"Paparangi",
"Paparoa",
"Paparoa National Park",
"Paparore",
"Papatawa",
"Papatotara",
"Papatowai",
"Papawai",
"Paraite",
"Parakai",
"Parakao",
"Parapara",
"Paraparaumu",
"Parau",
"Parawa",
"Parawera",
"Parekura Bay",
"Paremoremo",
"Pareora",
"Pareora West",
"Paretai",
"Parewanui",
"Parikino",
"Paringa",
"Park Hill",
"Parklands",
"Parkvale",
"Paroa",
"Parore",
"Parua Bay",
"Pataua",
"Patea",
"Patearoa",
"Patetonga",
"Patoka",
"Patons Rock",
"Patumahoe",
"Patutahi",
"Pauanui",
"Pauatahanui",
"Pawarenga",
"Pebbly Hill",
"Peebles",
"Peel Forest",
"Pegasus",
"Peka Peka",
"Peketa",
"Pelorus Bridge",
"Pembroke",
"Pendarves",
"Pepepe",
"Pepin Island",
"Peraki",
"Peria",
"Piano Flat",
"Piarere",
"Picton",
"Pigeon Bay",
"Pigeon Valley",
"Piha",
"Pihama",
"Piko Piko",
"Pikowai",
"Pine Bush",
"Pine Hill",
"Piopio",
"Pipiriki",
"Pipiroa",
"Pipiwai",
"Pirinoa",
"Pirongia",
"Pitone",
"Pleasant Point",
"Pleasant Valley",
"Plimmerton",
"Pohangina",
"Pohara",
"Pohokura",
"Pohuehue",
"Point Elizabeth",
"Point Wells",
"Pokeno",
"Pokuru",
"Pollok",
"Pomahaka",
"Pomarangai",
"Ponatahi",
"Pongakawa",
"Pongaroa",
"Poolburn",
"Poplars Range",
"Popotunoa",
"Poraiti",
"Porangahau",
"Porirua",
"Poroporo",
"Poroti",
"Poroutawhao",
"Port Albert",
"Port Chalmers",
"Port Charles",
"Port Jackson",
"Port Levy",
"Port Ligar",
"Port Underwood",
"Port Waikato",
"Portage",
"Portland",
"Portobello",
"Potaka",
"Potters",
"Pouawa",
"Poukawa",
"Pounawea",
"Pourakino Valley",
"Pourerere",
"Pouto",
"Prebbleton",
"Preece Point",
"Prices Valley",
"Progress Valley",
"Pudding Hill",
"Puhi Puhi",
"Puhoi",
"Pukahu",
"Pukaki",
"Pukeatua",
"Pukeawa",
"Pukehamoamoa",
"Pukehina",
"Pukehuia",
"Pukeiti",
"Pukekawa",
"Pukekohe",
"Pukekohe East",
"Pukekura",
"Pukemaori",
"Pukemiro",
"Pukemoremore",
"Pukengahu",
"Pukenui",
"Pukeokahu",
"Pukepoto",
"Pukerangi",
"Pukerau",
"Pukerua Bay",
"Puketaha",
"Puketapu",
"Puketi",
"Puketi Forest",
"Puketiro",
"Puketitiri",
"Puketoi",
"Puketotara",
"Puketutu",
"Pukeuri",
"Pumpkin Hill",
"Punakaiki",
"Punakitere Valley",
"Punaruku",
"Punga Cove",
"Pungarehu",
"Puni",
"Puniwhakau",
"Puponga",
"Purakauiti",
"Purakaunui",
"Puramahoi",
"Purangi",
"Purau",
"Purekireki",
"Pureora Forest Park",
"Puriri",
"Purua",
"Putaruru",
"Putauaki",
"Putere",
"Putorino",
"Puwera",
"Pyes Pa",
"Pyramid Valley",
"Quailburn",
"Quarry Hills",
"Queens Flat",
"Queensberry",
"Queenstown",
"Queenstown Hill",
"Rabbit Island",
"Raes Junction",
"Raetihi",
"Raglan",
"Rahotu",
"Rahu Saddle",
"Rai Valley",
"Rakahouka",
"Rakaia",
"Rakino Island",
"Rakopi",
"Ramarama",
"Ranana",
"Ranfurly",
"Rangataua",
"Rangihaeata",
"Rangiora",
"Rangiotu",
"Rangipo",
"Rangiriri",
"Rangiriri West",
"Rangitaiki",
"Rangitata",
"Rangitata Island",
"Rangitoto",
"Rangitumau",
"Rangiuru",
"Rangiwaea",
"Rangiwahia",
"Rankleburn",
"Ranui",
"Rapahoe",
"Rapaki",
"Rapaura",
"Rarangi",
"Ratana",
"Ratapiko",
"Raukawa",
"Raupunga",
"Raurimu",
"Rawene",
"Rawhiti",
"Rawhitiroa",
"Raymonds Gap",
"Red Beach",
"Redan",
"Redvale",
"Redwood Pass",
"Redwood Valley",
"Reefton",
"Reidston",
"Reikorangi",
"Renwick",
"Reporoa",
"Rere",
"Rerewhakaaitu",
"Retaruke",
"Rewa",
"Richmond",
"Richmond Downs",
"Rimu",
"Rimutaka Forest Park",
"Rimutaka Hill",
"Rings Beach",
"Ringway",
"Riponui",
"Rissington",
"Riverdale",
"Riverhead",
"Riverlands",
"Riverlea",
"Riversdale",
"Riversdale Beach",
"Riverside",
"Riverstone Terraces",
"Riverton",
"Riverton Racecourse",
"Riverton/Aparima",
"Riwaka",
"Robin Hood Bay",
"Robinsons Bay",
"Rock And Pillar",
"Rockville",
"Rolleston",
"Romahapa",
"Rongahere",
"Rongotea",
"Rosebery",
"Rosedale",
"Rosewill",
"Roslyn Bush",
"Ross",
"Rotherham",
"Rotoiti Forest",
"Rotokauri",
"Rotokawa",
"Rotoma",
"Rotongaro",
"Rotoorangi",
"Rotoroa",
"Rotorua",
"Rototuna North",
"Rotowaro",
"Round Hill",
"Rowallan",
"Roxburgh",
"Roxburgh East",
"Roys Hill",
"Ruahine",
"Ruahine Forest Park",
"Ruakaka",
"Ruakituri",
"Ruakokoputuna",
"Ruamahunga",
"Ruapuna",
"Ruatahuna",
"Ruatangata West",
"Ruatapu",
"Ruatiti",
"Ruatoki",
"Ruatoria",
"Ruawai",
"Ruawaro",
"Ruby Bay",
"Rukuhia",
"Runanga",
"Runciman",
"Russell",
"Rutherglen",
"Ryal Bush",
"Saddle Hill",
"Saint Andrews",
"Saint Arnaud",
"Saint Bathans",
"Saint James Range",
"Saint Omer",
"Saint Patricks",
"Salisbury",
"Sandspit",
"Sandstone",
"Sandy Point",
"Sandymount",
"Sanson",
"Santoft",
"Scarborough",
"Scargill",
"Schnapper Rock",
"Scotts Gap",
"Scroggs Hill",
"Seacliff",
"Seadown",
"Seaview",
"Seaward Bush",
"Seaward Downs",
"Seaward Valley",
"Seddon",
"Seddonville",
"Sefton",
"Sentry Hill",
"Serpentine",
"Shag Point",
"Shakespeare Bay",
"Shannon",
"Sheffield",
"Shelly Beach",
"Shenandoah",
"Sherenden",
"Shingle Creek",
"Silverdale",
"Simpsons Beach",
"Six Mile",
"Skippers",
"Slipper Island",
"Slope Point",
"Slopedown",
"Snells Beach",
"Snowdon",
"South Featherston",
"South Head",
"South Hillend",
"Southbridge",
"Southburn",
"Spar Bush",
"Speargrass Flat",
"Spotswood",
"Spring Creek",
"Springdale",
"Springfield",
"Springhills",
"Springlands",
"Springs Junction",
"Springston",
"Springvale",
"Squally Cove",
"Stag And Spey",
"Stanley Brook",
"Starvation Hill",
"Station Peak",
"Staveley",
"Steeple Burn",
"Stewart Island",
"Stillwater",
"Stirling",
"Stony Creek",
"Stratford",
"Strathmore",
"Stronvar",
"Styx",
"Summer Hill",
"Surrey Hills",
"Sutherlands",
"Sutton",
"Swannanoa",
"Swanson",
"Table Mound",
"Tadmor",
"Tahakopa",
"Tahakopa Valley",
"Taharoa",
"Taharua",
"Tahawai",
"Taheke",
"Tahora",
"Tahorakuri Forest",
"Tahuna",
"Taieri Beach",
"Taieri Mouth",
"Taihape",
"Taiharuru",
"Taiko",
"Taipa",
"Taipuha",
"Tairua",
"Taitapu",
"Takahiwai",
"Takahue",
"Takaka",
"Takaka Hill",
"Takamatua",
"Takanini",
"Takapau",
"Takapu Valley",
"Takaro",
"Tamahere",
"Tamatea",
"Tamaterau",
"Taneatua",
"Tangarakau",
"Tangimoana",
"Tangiteroria",
"Tangiwai",
"Tangoio",
"Tangowahine",
"Tanners Point",
"Taoroa Junction",
"Tapanui",
"Tapapa",
"Tapawera",
"Tapora",
"Tapu",
"Tapui",
"Taradale",
"Taramoa",
"Taranui",
"Tarara",
"Tararu",
"Tarata",
"Tarawera",
"Tarawera Forest",
"Tariki",
"Taringamotu",
"Taringatura",
"Tarras",
"Taruheru",
"Tarurutangi",
"Tasman",
"Tata Beach",
"Tataraimaka",
"Tatuanui",
"Tauhara",
"Tauhara Forest",
"Tauhei",
"Tauherenikau",
"Tauhoa",
"Taumarunui",
"Taumata Island",
"Taunoka",
"Taupaki",
"Taupiri",
"Taupo",
"Taupo Bay",
"Tauranga",
"Tauranga Taupo",
"Tauriko",
"Tautoro",
"Tauweru",
"Tawa",
"Tawanui",
"Tawera",
"Tawharanui Peninsula",
"Taylor Pass",
"Taylorville",
"Te Akau",
"Te Anau",
"Te Anau Downs",
"Te Anga",
"Te Arai",
"Te Araroa",
"Te Aroha",
"Te Aroha West",
"Te Awaiti",
"Te Awamutu",
"Te Awanga",
"Te Hana",
"Te Hapua",
"Te Haroto",
"Te Hauke",
"Te Haumi",
"Te Hoe",
"Te Horo",
"Te Horo Beach",
"Te Houka",
"Te Kaha",
"Te Kao",
"Te Karaka",
"Te Kauwhata",
"Te Kawa",
"Te Kiri",
"Te Kiteroa",
"Te Kohanga",
"Te Kopuru",
"Te Kouma",
"Te Kowhai",
"Te Kuiti",
"Te Mahia",
"Te Mapara",
"Te Marua",
"Te Mata",
"Te Miro",
"Te Muna",
"Te Ohaki",
"Te Oka",
"Te Onepu",
"Te Ore Ore",
"Te Pahu",
"Te Pohue",
"Te Poi",
"Te Popo",
"Te Puia Springs",
"Te Puke",
"Te Puna",
"Te Puninga",
"Te Puru",
"Te Ranga",
"Te Rauamoa",
"Te Rerenga",
"Te Roti",
"Te Teko",
"Te Tii",
"Te Tipua",
"Te Towaka",
"Te Uku",
"Te Uri",
"Te Waewae",
"Te Wera",
"Te Wharau",
"Te Whiti",
"Teddington",
"Tekapo",
"Tekapo Military Camp",
"Tekoa Range",
"Temple View",
"Templeton",
"Temuka",
"Tennyson Inlet",
"Teschemakers",
"Teviot",
"Teviotdale",
"Thames",
"The Brook",
"The Gardens",
"The Key",
"The Neck",
"The Peaks",
"The Pines Beach",
"The Plateau",
"Thomsons Crossing",
"Thomsons Ford",
"Thornbury",
"Thornton",
"Thornton Bay",
"Thorpe",
"Ti Point",
"Tiakitahuna",
"Tihaka",
"Tihiroa",
"Tihoi",
"Tikitere",
"Tikitiki",
"Tikokino",
"Tikorangi",
"Timaru",
"Timberlea",
"Tiniroto",
"Tinopai",
"Tinui",
"Tinui Valley",
"Tinwald",
"Tirau",
"Tiraumea",
"Tirohanga",
"Tirohia",
"Tiroiti",
"Tisbury",
"Titirangi",
"Titoki",
"Titri",
"Tiwai Point",
"Toatoa",
"Todds Valley",
"Tohunga Junction",
"Tokaanu",
"Tokanui",
"Tokaora",
"Tokarahi",
"Tokirima",
"Toko",
"Toko Mouth",
"Tokomaru",
"Tokomaru Bay",
"Tokoroa",
"Tolaga",
"Tolaga Bay",
"Tomarata",
"Tomoana",
"Tongaporutu",
"Tongariro",
"Tongariro Forest Park",
"Tongariro National Park",
"Topuni",
"Tora",
"Torere",
"Torrent Bay",
"Totara",
"Totara Flat",
"Totara North",
"Totara Park",
"Totara Peak",
"Totara River",
"Totara Valley",
"Totaranui",
"Towai",
"Treble Cone",
"Tuahiwi",
"Tuai",
"Tuakau",
"Tuamarina",
"Tuapeka Flat",
"Tuapeka Mouth",
"Tuapeka West",
"Tuatapere",
"Tuateawa",
"Tuki Tuki",
"Tumunui",
"Turakina",
"Turangaomoana",
"Turangi",
"Turitea",
"Turiwhate",
"Turiwiri",
"Turua",
"Tussock Creek",
"Tutaki",
"Tutira",
"Tutukaka",
"Tuturau",
"Tuturumuri",
"Tututawa",
"Twinlaw",
"Twizel",
"Twyford",
"Umawera",
"Underwood",
"Upokongaro",
"Upper Charlton",
"Upper Hutt",
"Upper Moutere",
"Upper Plain",
"Upper Takaka",
"Upper Waitati",
"Urenui",
"Urewera National Park",
"Uruti",
"Uruwhenua",
"Utiku",
"Valetta",
"Victoria Forest Park",
"View Hill",
"Virginia",
"Waddington",
"Waerenga",
"Waharoa",
"Wai-Iti",
"Waianakarua",
"Waianiwa",
"Waiareka Junction",
"Waiaro",
"Waiatarua",
"Waiau",
"Waiau Pa",
"Waihaha",
"Waihakeke",
"Waihao Downs",
"Waihaorunga",
"Waiharara",
"Waihau Bay",
"Waiheke Island",
"Waihemo",
"Waihi",
"Waihi Beach",
"Waiho",
"Waihoaka",
"Waihola",
"Waihopai",
"Waihopai Valley",
"Waihou",
"Waiinu Beach",
"Waiiti",
"Waikaia",
"Waikaka",
"Waikaka Valley",
"Waikana",
"Waikanae",
"Waikare",
"Waikaretu",
"Waikari",
"Waikaura",
"Waikawa",
"Waikawa Beach",
"Waikawa Valley",
"Waikawau",
"Waikeria",
"Waikerikeri",
"Waikino",
"Waikite Valley",
"Waikoikoi",
"Waikokowai",
"Waikouaiti",
"Waikouro",
"Waikuku",
"Waikuku Beach",
"Waima",
"Waimahaka",
"Waimahora",
"Waimairi Beach",
"Waimamaku",
"Waimana",
"Waimangaroa",
"Waimangu",
"Waimarama",
"Waimarino",
"Waimate",
"Waimate North",
"Waimatua",
"Waimatuku",
"Waimauku",
"Waimea",
"Waimiha",
"Waimumu",
"Waingaro",
"Waingawa",
"Wainui",
"Wainuiomata",
"Wainuiomata Coast",
"Wainuioru",
"Waioeka",
"Waiohau",
"Waiohiki",
"Waiomio",
"Waiomu",
"Waione",
"Waiongana",
"Waiotahi",
"Waiotahi Valley",
"Waiotapu",
"Waiotira",
"Waiou",
"Waiouru",
"Waipa Valley",
"Waipahi",
"Waipango",
"Waipapa",
"Waipapa Bay",
"Waipapakauri",
"Waipara",
"Waiparu",
"Waipatu",
"Waipawa",
"Waipiata",
"Waipori",
"Waipori Falls",
"Waipoua Forest",
"Waipounamu",
"Waipu",
"Waipukurau",
"Waipunga",
"Wairakei",
"Wairakei Village",
"Wairaki",
"Wairau Valley",
"Wairio",
"Wairoa",
"Wairoa Valley",
"Wairuna",
"Waitaanga",
"Waitahanui",
"Waitahora",
"Waitahuna",
"Waitahuna Gully",
"Waitahuna West",
"Waitaia Bay",
"Waitakaruru",
"Waitakere",
"Waitaki Bridge",
"Waitane",
"Waitane West",
"Waitangi",
"Waitao",
"Waitara",
"Waitarere",
"Waitaria Bay",
"Waitata",
"Waitati",
"Waitepeka",
"Waiterimu",
"Waitetuna",
"Waitoa",
"Waitohi",
"Waitoki",
"Waitomo",
"Waitotara",
"Waitui",
"Waituna West",
"Waiuku",
"Waiwera",
"Waiwera South",
"Waiwhakaiho",
"Waiwhare",
"Wakamarina",
"Wakanui",
"Wakapatu",
"Wakapuaka",
"Wakefield",
"Waldronville",
"Wallacetown",
"Wallingford",
"Walter Peak",
"Walton",
"Wanaka",
"Wangaloa",
"Wanganui",
"Wanganui East",
"Wanstead",
"Waotu",
"Ward",
"Wardville",
"Warea",
"Warepa",
"Warkworth",
"Warrington",
"Washdyke",
"Washdyke Flat",
"Waverley",
"Wayby Valley",
"Waynes",
"Weber",
"Wedderburn",
"Weka Pass",
"Welcome Bay",
"Wellington",
"Wellsford",
"Wendon",
"Wendon Valley",
"Wendonside",
"Weraiti",
"West Dome",
"West End",
"West Eyreton",
"West Melton",
"West Plains",
"West Taratahi",
"Westerfield",
"Western Lake",
"Westland National Park",
"Westmere",
"Weston",
"Westport",
"Westshore",
"Westwood",
"Wether Hill",
"Whakaki",
"Whakamarama",
"Whakamaru",
"Whakapara",
"Whakapirau",
"Whakarewarewa",
"Whakarongo",
"Whakataki",
"Whakatane",
"Whakatete Bay",
"Whakatiwai",
"Whakatu",
"Whanaehu Valley",
"Whananaki",
"Whanawhana",
"Whangaehu",
"Whangaimoana",
"Whangamarino",
"Whangamata",
"Whangamoa",
"Whangamomona",
"Whanganui National Park",
"Whangaparaoa",
"Whangapoua",
"Whangarei",
"Whangarei Heads",
"Whangaripo",
"Whangaroa",
"Whangaruru",
"Whangateau",
"Whare Creek",
"Whareama",
"Wharehine",
"Whareora",
"Wharepapa South",
"Wharepuhunga",
"Wharerata",
"Whareroa",
"Wharetoa",
"Wharewaka",
"Whatamango Bay",
"Whataroa",
"Whatatutu",
"Whataupoko",
"Whatawhata",
"Wheki Valley",
"Whenuakite",
"Whenuanui Bay",
"Whenuapai",
"Whirinaki",
"Whirinaki Forest Park",
"Whiritoa",
"Whitby",
"White Pine Bush",
"White Rock",
"Whitemans Valley",
"Whiterigg",
"Whitford",
"Whitianga",
"Whitikahu",
"Whitstone",
"Wilden",
"Willowbank",
"Willowby",
"Wiltsdown",
"Winchester",
"Winchmore",
"Windsor",
"Windsor Park",
"Windwhistle",
"Winslow",
"Winton",
"Witherlea",
"Woodbourne",
"Woodbury",
"Woodend",
"Woodend Beach",
"Woodhill Forest",
"Woodlands",
"Woodlaw",
"Woodside",
"Woodstock",
"Woodville",
"Wreys Bush",
"Wrights Bush",
"Wye Creek",
"Wyndham",
"Wyuna Bay",
"Yaldhurst"
]