<div id="sidebar">


<div id="sidebarlinks">
  
<div class="block">

<h2>Job vacancy websites</h2>

<div class="topBottomFloat"><a href="http://job-bank.workandincome.govt.nz/find-a-job/search.aspx" title="Find a Job"><img src="http://www.workandincome.govt.nz/images/online-services/button-find-a-job.gif"  width="130" height="59" alt="Find a Job" /></a></div>

<div class="topBottomFloat"><a href="http://www.seek.co.nz/" title="SEEK"><img src="http://www.workandincome.govt.nz/images/logos/seek-nz-logo.gif" width="130" height="52" alt="SEEK" /></a></div>

<div class="topBottomFloat"><a href="http://www.trademe.co.nz/jobs" title="Trade Me Jobs"><img src="http://www.workandincome.govt.nz/images/logos/trademe-jobs-130-right-nav.gif"  width="130" height="51" alt="Trade Me Jobs" /></a></div>

<div class="topBottomFloat"><a href="http://www.careers.govt.nz/" title="Careers NZ"><img src="http://www.workandincome.govt.nz/images/logos/career-services-logo.gif"  width="130" height="51" alt="Careers NZ" /></a></div>
</div>

<div class="block">
<h2>Related information</h2>
<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/using-find-a-job.html">How to use Find a Job</a></div>
<div class="links website"><a href="http://www2.careers.govt.nz/index.php?id=4676">Careers NZ - How to get a job</a></div>

<h2>Downloads</h2>
<div class="links pdf"><a href="http://www.workandincome.govt.nz/documents/find-a-job-build-a-future.pdf">Find a job build a future</a></div>
</div>

</div><!-- div="sidebarlinks" -->


</div><!-- div="sidebar" -->