<div id="handy">

<div class="resources">

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/starting-your-job-search.html">Starting your job search</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/cvs-and-covering-letters.html">Writing your CV and covering</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/where-to-look.html">Where to look</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/job-leads.html">Finding job leads</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/applying-for-jobs-tips.html">Appling for a job</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/job-interview.html">Job interviews</a></div>

<div class="links default"><a href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/get-the-job.html">When you get the job</a></div>

<div class="links website"><a href="http://jobs.nzherald.co.nz/">jobs.nzherald.co.nz</a></div>

<div class="links website"><a href="http://www.jobs.co.nz/">www.jobs.co.nz</a></div>

<div class="links website"><a href="http://www.bestjobs.co.nz/">www.bestjobs.co.nz</a></div>

<div class="links website"><a href="https://jobs.govt.nz/">jobs.govt.nz</a></div>

<div class="links website"><a href="http://careers.msd.govt.nz/login.aspx?coid=210">www.msd.govt.nz/careers</a></div>

<div class="links website"><a href="http://www.greensky.co.nz/">Green sky - hire and be hire</a></div>

<div class="links website"><a href="http://www.sjs.co.nz/search/jobs">Student Job Search</a></div>

<div class="links website"><a href="http://nz.indeed.com/">Indeed.com</a></div>

<div class="links website"><a href="http://myjobspace.co.nz/">myjobspace.co.nz</a></div>

<div class="links website"><a href="http://www.hospotrade.co.nz/Jobs">Hospotrade - Hospitality jobs</a></div>

</div><!-- End resources -->
</div><!-- End handy -->