<div id="handy">

<h2>Handy</h2>

<div class="resources">
<div class="block">

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/starting-your-job-search.html">Starting your job search</a>

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/cvs-and-covering-letters.html">Writing your CV and covering</a>

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/where-to-look.html">Where to look</a>

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/job-leads.html">Finding job leads</a>

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/applying-for-jobs-tips.html">Appling for a job</a>

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/job-interview.html">Job interviews</a>

<a class="links default" href="http://www.workandincome.govt.nz/individuals/looking-for-work/job-search-tips/get-the-job.html">When you get the job</a>

<a class="links website" href="http://jobs.nzherald.co.nz/">jobs.nzherald.co.nz</a>

<a class="links website" href="http://www.jobs.co.nz/">www.jobs.co.nz</a>

<a class="links website" href="http://www.bestjobs.co.nz/">www.bestjobs.co.nz</a>

<a class="links website" href="https://jobs.govt.nz/">jobs.govt.nz</a>

<a class="links website" href="http://careers.msd.govt.nz/login.aspx?coid=210">www.msd.govt.nz/careers</a>

<a class="links website" href="http://www.greensky.co.nz/">Green sky - hire and be hired</a>

<a class="links website" href="http://www.sjs.co.nz/search/jobs">Student Job Search</a>

<a class="links website" href="http://nz.indeed.com/">Indeed.com</a>

<a class="links website" href="http://myjobspace.co.nz/">myjobspace.co.nz</a>

<a class="links website" href="http://www.hospotrade.co.nz/Jobs">Hospotrade - Hospitality jobs</a>
</div>
</div><!-- End resources -->
</div><!-- End handy -->