area1 = [
"Albany",
"Army Bay",
"Awaruku",
"Bayswater",
"Beachhaven North",
"Beachhaven South",
"Birkdale North",
"Birkdale South",
"Birkenhead East",
"Browns Bay",
"Campbells Bay",
"Castor Bay",
"Chelsea",
"Crown Hill",
"Dairy Flat-Redvale",
"Forrest Hill",
"Glamorgan",
"Glendhu",
"Glenfield Central",
"Glenfield North",
"Greenhithe",
"Gulf Harbour",
"Hatfields Beach",
"Hauraki",
"Kaipatiki",
"Kauri Park",
"Lake Pupuke",
"Long Bay",
"Mairangi Bay",
"Manly",
"Monarch Park",
"Murrays Bay",
"Mt Victoria",
"Narrow Neck",
"Northcote South",
"Northcross",
"North Harbour",
"Oaktree",
"Ocean View",
"Orewa",
"Paremoremo East",
"Paremoremo West",
"Pinehill",
"Red Beach",
"Rothesay Bay",
"Seacliffe",
"Silverdale North",
"Silverdale South",
"Stanley Bay",
"Stanmore Bay",
"Sunnybrae",
"Sunnynook",
"Takapuna Central",
"Target Road",
"Torbay",
"Tuff Crater",
"Unsworth Heights",
"Waiake",
"Waiwera",
"Westlake",
"Windy Ridge",
"Witheford",
"Abbotts Park",
"Akarana",
"Auckland Central West",
"Auckland Central East",
"Auckland Harbourside",
"Arch Hill",
"Avondale South",
"Avondale West",
"Balmoral",
"Blockhouse Bay",
"Eden Terrace",
"Epsom Central",
"Epsom North",
"Epsom South",
"Ellerslie North",
"Ellerslie South",
"Ferndale",
"Freemans Bay",
"Glenavon",
"Glendowie",
"Glen Innes East",
"Glen Innes North",
"Glen Innes West",
"Grafton East",
"Grafton West",
"Grey Lynn East",
"Grey Lynn West",
"Hamlin",
"Herne Bay",
"Hillsborough East",
"Hillsborough West",
"Kingsland",
"Kohimarama East",
"Kohimarama West",
"Lynfield North",
"Lynfield South",
"Maungawhau",
"Meadowbank North",
"Meadowbank South",
"Mission Bay",
"Mt Albert Central",
"Mt Eden East",
"Mt Eden North",
"Mt Eden South",
"Mt Hobson",
"Mt St John",
"Mt Wellington North",
"Mt Wellington South",
"Newmarket",
"Newton",
"New Windsor",
"One Tree Hill Central",
"One Tree Hill East",
"Onehunga North East",
"Onehunga North West",
"Onehunga South West",
"Onehunga South East",
"Orakei North",
"Orakei South",
"Oranga",
"Otahuhu East",
"Otahuhu West",
"Owairaka West",
"Owairaka East",
"Panmure Basin",
"Parnell East",
"Parnell West",
"Penrose",
"Point Chevalier West",
"Point Chevalier East",
"Point Chevalier South",
"Point England",
"Ponsonby East",
"Ponsonby West",
"Remuera South",
"Remuera West",
"Roberton",
"Rosebank",
"Royal Oak",
"Sandringham East",
"Sandringham North",
"Sandringham West",
"Sherbourne",
"Springleigh",
"St Heliers",
"StJohns",
"St Lukes",
"St Lukes North",
"St Marys",
"Surrey Crescent",
"Tamaki",
"Te Papapa",
"Three Kings",
"Waiata",
"Waikowhai East",
"Waikowhai West",
"Waitaramoa",
"Walmsley",
"Waterview",
"Wesley",
"Westmere"]