area2 = [
"Wellsford",
"Warkworth",
"Snells Beach",
"Hellensville",
"Waiheke Island",
"South Waiuku",
"Waiuku",
"Armour Bay",
"Birdwood",
"Crum Park",
"Durham Green",
"Edmonton",
"Fairdene",
"Freemans Bay",
"Fruitvale",
"Glen Eden East",
"Glendene North",
"Glendene South",
"Green Bay",
"Henderson North",
"Henderson South",
"Herald",
"Hobsonville",
"Kaurilands",
"Kelston Central",
"Kingdale",
"Konini",
"Kumeu",
"Laingholm",
"Lucken Point",
"Matipo",
"Mcleod",
"New Lynn North",
"Opanuku",
"Otimai",
"Parrs Park",
"Ranui North",
"Rewarewa",
"Royal Heights",
"Royal Road West",
"Sunnyvale",
"Sturges North",
"Sturges South",
"Swanson",
"Tangutu",
"Taupaki",
"Te Atatu Central",
"Titirangi South",
"Waimumu North",
"Waimumu South",
"Waipareira West",
"Waima",
"Wakeling",
"Whenuapai West",
"Westgate",
"Woodglen",
"West Harbour ",
"West Massey",
"Aberfeldy",
"Ambury",
"Aorere",
"Arahanga",
"Ardmore",
"Beaumont",
"Beachlands-Maraetai",
"Bleakhouse",
"Botany Downs",
"Bremner",
"Bucklands and Eastern Beaches",
"Bucklands Beach South",
"Burbank",
"Burswood",
"Clendon",
"Clover Park",
"Cockle Bay",
"Dannemora",
"Dingwall",
"Donegal Park",
"Drury",
"East Tamaki",
"Edgewater",
"Elsmore Park",
"Favona",
"Ferguson",
"Flat Bush",
"Golfland",
"Grange",
"Half Moon Bay",
"Harania East",
"Harania North",
"Harania West",
"Hill Park",
"Hingaia",
"Homai East",
"Homai West",
"Howick Central",
"Howick West",
"Hyperion",
"Kilkenny",
"Kohuora",
"Leabank",
"Mangere Bridge",
"Mangere Central",
"Mangere East",
"Mangere South",
"Mangere Station",
"Manukau Central",
"Manurewa Central",
"Manurewa East",
"Mascot",
"Massey Park",
"Maungamaungaroa",
"Mellons Bay",
"Middlemore",
"Millhouse",
"Murvale",
"Ormiston",
"Opaheke",
"Otara East",
"Otara North",
"Otara South",
"Otara West",
"Pahurehure",
"Pakuranga Central",
"Pakuranga East",
"Pakuranga North",
"Papakura Central",
"Papakura North",
"Papakura South",
"Papakura East",
"North East Papakura",
"Papatoetoe West",
"Papatoetoe North",
"Papatoetoe Central",
"Papatoetoe East",
"Pigeon Mountain North",
"Pigeon Mountain South",
"Point View",
"Puhinui",
"Randwick Park",
"Red Hill",
"Redoubt North",
"Redoubt South",
"Rosehill",
"Rowandale",
"Runciman",
"Shelly Park",
"Sunnyhills",
"Takanini North",
"Takanini South",
"Takanini West",
"Totara Heights",
"Turanga",
"Viscount",
"Wairere",
"Wattle Farm Weymouth",
"Whangapouri Creek",
"Wiri",
"Algies Bay - Mahurangi",
"Awhitu",
"Bombay",
"Cape Rodney",
"Clevedon",
"Glenbrook",
"Great Barrier Island",
"Hunua",
"Karekare",
"Kaukapakapa",
"Kawau",
"Kingseat",
"Leigh",
"Little Barrier Island",
"Mangatawhiri",
"Maramarua",
"Matheson Bay",
"Meremere",
"Motutapu Island",
"Muriwai Beach",
"Onewhero",
"Otaua",
"Parakai",
"Patumahoe",
"Pokeno",
"Rakino Island",
"Rangitoto Island",
"Rewiti",
"Riverhead",
"South Head",
"Tahekeroa",
"Tauhoa - Puhoi",
"Bledisloe Park",
"Buckland",
"Eden Road-Hill Top",
"Opuawhanga",
"Paerata-Cape Hill",
"Pukekohe North",
"Pukekohe West",
"Redoubt",
"Tuakau",
"Arataki",
"Bellevue",
"Bethlehem",
"Bethlehem East",
"Gate Pa Greerton",
"Hairini",
"Judea",
"Kairua",
"Matapihi",
"Matua",
"Maunga",
"Motuopae Island",
"Mt Maunganui North",
"Maungatapu",
"Ohauiti-Ngapeke",
"Omanu",
"Omokoroa Community",
"Otumoetai North",
"Otumoetai South",
"Papamoa Beach East",
"Papamoa Beach West",
"Poike",
"Pyes Pa",
"Sulphur Point",
"Tauranga Central",
"Tauranga Hospital",
"Tauranga South",
"Te Brookfield",
"Te Puna",
"Te Reti",
"Welcome Bay",
"Yatton Park",
"Adelaide",
"Aro Street-Nairn Street",
"Awarua",
"Berhampore",
"Brooklyn",
"Brooklyn South",
"Central Tawa",
"Churton",
"Churton Park",
"Greenacres",
"Grenada",
"Grenada North",
"Happy Valley-Owhiro Bay",
"Hataitai",
"Island Bay East",
"Island Bay West",
"Johnsonville East",
"Johnsonville North",
"Johnsonville South",
"Johnston Hill",
"Kaiwharawhara",
"Karaka Bay-Worser Bay",
"Karori East",
"Karori Park",
"Kelburn",
"Khandallah Park",
"Kilbirnie East",
"Kilbirnie West",
"Kingston",
"Lambton",
"Linden",
"Lyall Bay",
"Maupuia",
"Melrose",
"Miramar North",
"Miramar South",
"Mitchelltown",
"Mt Cook-Wallace Street",
"Mt Victoria West",
"Newlands East",
"Newlands North",
"Newlands South",
"Newtown East",
"Newtown West",
"Ngaio",
"Ngauranga East",
"Ngauranga West",
"Northland",
"Oriental Bay",
"Paparangi",
"Rangoon Heights",
"Raroa",
"Roseneath",
"Seatoun",
"Strathmore Park",
"Taitville",
"Tawa South",
"Te Kainga",
"Thorndon-Tinakori Road",
"Vogeltown",
"Wadestown",
"Willis Street-Cambridge Terrace",
"Wilton-Otari",
"Wright Hill",
"Aniseed Hil",
"Atawhai",
"Atmore",
"Bell Island",
"Best Island",
"Britannia Heights",
"Broads",
"Bronte",
"Clifton",
"Enner Glynn",
"Glenduan",
"Grampians",
"Hope",
"Isel Park",
"Kirks",
"Langbein",
"Maitai",
"Maitlands",
"Nayland",
"Nelson Airport",
"Ngawhatu",
"Port Nelson",
"Ranzau",
"Richmond North",
"Richmond South",
"Saxton",
"Saxton Island",
"Tahuna Hills",
"Tahunanui",
"The Brook",
"The Wood",
"Toi Toi",
"Trafalgar",
"Wakefield",
"Brightwater",
"Wanaka",
"Arrowtown",
"Earnslaw",
"Frankton",
"Kelvin Heights",
"Queenstown Bay",
"Sunshine Bay"]