area3 = [
"Taipa Bay-Mangonui",
"Kaitaia East",
"Kaitaia West",
"Kerikeri",
"Russell",
"Paihia",
"Abbey Caves",
"Hikurangi",
"Horahora",
"Kamo East",
"Kamo West",
"Kensington",
"Mairtown",
"Maunu",
"Morningside",
"Onerahi",
"Otaika-Portland",
"Otangarei",
"Parahaki",
"Port-Limeburners",
"Raumanga East",
"Raumanga West",
"Regent",
"Riverside",
"Sherwood Rise",
"Springs Flat",
"Te Hihi",
"Three Mile Bush",
"Tikipunga East",
"Tikipunga West",
"Vinetown",
"Western Hills",
"Whangarei Central",
"Whau Valley",
"Woodhill",
"Whitianga",
"Whangamata",
"Thames",
"Tairua",
"Waihi Beach",
"Katikati Communty",
"Te Puke East",
"Te Puke West",
"Matamata",
"Allandale-Mokorua",
"Coastlands",
"Maraetotara",
"Ohope Orini Poroporo",
"Trident",
"Whakatane North",
"Whakatane West",
"Bader",
"Beerescourt",
"Bryant",
"Brymer",
"Burbush",
"Chartwell",
"Chedworth",
"Clarkin",
"Claudelands",
"Dinsdale North",
"Dinsdale South",
"Enderley",
"Eureka",
"Fairview Downs",
"Flagstaff",
"Frankton Junction",
"Glenview",
"Gordonton",
"Hamilton Central",
"Hamilton East",
"Hamilton Lake",
"Hillcrest West",
"Horotiu",
"Horsham Downs",
"Huntington",
"Insoll",
"Kainui",
"Kaipaki",
"Lake Cameron",
"Maeroa",
"Melville",
"Nawton",
"Naylor",
"Ngahinapouri",
"Ngaruawahia",
"Ohaupo",
"Peachgrove",
"Peacocke",
"Porritt",
"Pukete",
"Pukete West",
"Queenwood",
"Riverlea",
"Rotokauri",
"Rototuna",
"Silverdale",
"Swarbrick",
"Sylvester",
"Tamahere-Tauwhare",
"Taupiri Community",
"Te Kowhai",
"Te Rapa",
"Temple View",
"University",
"Whatawhata",
"Matangi",
"Cambridge Central",
"Cambridge North",
"Cambridge West",
"Hautapu",
"Leamington East",
"Leamington West",
"Pukerimu",
"Raglan",
"Allen Road",
"Kihikihi",
"Kihikihi Flat",
"Lake Ngaroto",
"Te Awamutu Central",
"Te Awamutu East",
"Te Awamutu South",
"Te Awamutu West",
"Te Rahu",
"Fairy Springs",
"Fenton",
"Fordlands",
"Glenholme East",
"Glenholme West",
"Hillcrest",
"Kawaha Point",
"Koutu",
"Kuirau",
"Lynmore",
"Mangakakahi",
"Ngapuna",
"Ngongotaha North",
"Ngongotaha South",
"Ohinemutu",
"Owhata East",
"Owhata South",
"Owhata West",
"Poets Corner",
"Pomare",
"Pukehangi North",
"Pukehangi South",
"Selwyn Heights",
"Springfield",
"Sunnybrook",
"Utuhina",
"Victoria",
"Western Heights",
"Whaka",
"Acacia Bay",
"Central Taupo",
"Hilltop",
"Lakewood",
"Maunganamu",
"Nukuhau",
"Rangatira",
"Rangatira Park",
"Richmond Heights",
"Tauhara",
"Taupo East",
"Waipahihi",
"Wairakei-Aratiatia",
"Wharewaka",
"Ahuriri",
"Awatoto",
"Bay View",
"Bluff Hill",
"Eskdale",
"Green meadows",
"Hospital Hill",
"Maraenui",
"Marewa",
"Mclean Park",
"Meeanee",
"Nelson Park",
"Onekawa Central",
"Onekawa South",
"Onekawa West",
"Pirimai",
"Poraiti",
"Tamatea North",
"Tamatea South",
"Taradale North",
"Taradale South",
"Waiohiki",
"Westshore",
"Akina",
"Anderson Park",
"Bridge Pa",
"Brookvale",
"Camberley",
"Clive",
"Flaxmere East",
"Frimley",
"Hastings Central",
"Haumoana",
"Iona",
"Irongate",
"Karamu",
"Kingsley-Chatham",
"Lochain",
"Longlands South",
"Mahora",
"Omahu",
"Pakipaki",
"Pakowhai",
"Parkvale",
"Raureka",
"St Leonards",
"Te Mata",
"Twyford",
"Whakatu",
"Woolwich",
"Barrett",
"Bell Block",
"Bowden",
"Carrington",
"Fernleigh",
"Fitzroy",
"Frankleigh",
"Glen Avon",
"Highlands Park",
"Kawaroa",
"Lynmouth",
"Mangaoraka",
"Marfell",
"Marsland Hill",
"Merrilands",
"Moturoa",
"Mount Bryan",
"New Plymouth Central",
"Oakura",
"Omata",
"Paraite",
"Spotswood",
"Struan Park",
"Upper Westown",
"Welbourn",
"Westown",
"Feilding Central",
"Feilding East",
"Feilding North",
"Feilding West",
"Maewa",
"Oroua Bridge",
"Aokautere Ashhurst",
"Awapuni North",
"Awapuni South",
"Awapuni West",
"Cloverlea",
"Highbury",
"Hokowhitu East",
"Hokowhitu Lagoon",
"Hokowhitu West",
"Kairanga",
"Kelvin Grove",
"Linton Military Camp",
"Longburn",
"Massey University",
"Milson",
"Palmerston North Central",
"Palmerston North Hospital",
"Papaeoia",
"Roslyn",
"Stoney Creek",
"Takaro",
"Terrace End",
"Westbrook",
"West End",
"Whakarongo",
"Otaihanga",
"Paekakariki",
"Paraparaumu Beach North",
"Paraparaumu Beach South",
"Paraparaumu Central",
"Peka Peka",
"Raumati Beach",
"Raumati South",
"Waikanae East",
"Waikanae Park",
"Waikanae West",
"Waikanae Beach",
"Adventure",
"Ascot Park",
"Cannons Creek East",
"Cannons Creek North",
"Cannons Creek South",
"Discovery",
"Elsdon-Takapuwahia",
"Endeavour",
"Mana-Camborne",
"Onepoto",
"Papakowhai",
"Paremata-Postgate",
"Pauatahanui",
"Plimmerton",
"Porirua Central",
"Porirua East",
"Pukerua Bay",
"Ranui Heights",
"Resolution",
"Titahi Bay North",
"Titahi Bay South",
"Waitangirua",
"Akatarawa",
"Brentwood",
"Clouston Park",
"Ebdentown",
"Elderslea",
"Emerald Hill",
"Heretaunga Park",
"Heretaunga-Silverstream",
"Maidstone",
"Maoribank",
"Moonshine",
"Pinehaven",
"Te Marua",
"Totara Park",
"Trentham North",
"Trentham South",
"Upper Hutt Central",
"Wallaceville",
"Alicetown",
"Arakura",
"Avalon East",
"Avalon West",
"Belmont",
"Boulcott",
"Delaney",
"Eastbourne",
"Epuni East",
"Epuni West",
"Esplanade",
"Fernlea",
"Glendale",
"Gracefield",
"Haywards-Manor Park",
"Holborn",
"Homedale East",
"Homedale West",
"Hutt Central",
"Kelson",
"Korokoro",
"Manuka",
"Maungaraki",
"Melling",
"Moera",
"Naenae North",
"Naenae South",
"Normandale",
"Parkway",
"Petone Central",
"Taita North",
"Taita South",
"Tawhai",
"Waiwhetu North",
"Waiwhetu South",
"Waterloo East",
"Waterloo West",
"Wilford",
"Woburn North",
"Woburn South",
"Cloustonville",
"Kapiti Island",
"Makara-Ohariu",
"Mana Island",
"Maungakotukutuku",
"Mangaroa",
"Nabhra",
"Opiki",
"Otaki",
"Paekakariki Hill",
"Pencarrow",
"Tokomaru",
"Takaka",
"Motueka East",
"Motueka West",
"Blenheim Central",
"Mayfield",
"Omaka",
"Spring Creek-Riverlands",
"Redwoodtown",
"Renwick",
"Springlands",
"Whitney",
"Witherlea",
"Woodbourne",
"Hanmer Springs",
"Woodend",
"Rangiora",
"Addington",
"Aorangi",
"Aranui",
"Avon Loop",
"Avondale",
"Avonhead",
"Avonside",
"Barrington North",
"Barrington South",
"Beckenham",
"Belfast",
"Bexley",
"Bishopdale",
"Bromley",
"Broomfield",
"Bryndwr",
"Burnside",
"Burwood",
"Camside",
"Casebrook",
"Cashmere East",
"Cashmere West",
"Cathedral Square",
"Chisnall",
"Clarkville",
"Dallington",
"Deans Bush",
"East Linwood",
"Edgeware",
"Ensors",
"Fendalton",
"Ferrymead",
"Hagley Park",
"Halswell East",
"Halswell South",
"Halswell West",
"Harewood",
"Hawthornden",
"Heathcote Valley",
"Hillmorton",
"Holmwood",
"Hoon Hay",
"Hoon Hay South",
"Hornby North",
"Hornby South",
"Ilam",
"Islington",
"Jellie Park",
"Kaiapoi North",
"Kaiapoi South",
"Kaiapoi West",
"Kaimahi",
"Kennedys Bush",
"Linwood",
"Mairehau",
"Marshland",
"Masham",
"Mcleans Island",
"Merivale",
"Merrin",
"Middleton",
"North Linwood",
"North Richmond",
"Northcote",
"Oaklands",
"Opawa",
"Papanui",
"Parklands",
"Phillipstown",
"Pines-Kairaki Beach",
"Prebbleton",
"Rapaki Track",
"Redwood North",
"Redwood South",
"Riccarton",
"Riccarton South",
"Riccarton West",
"Russley",
"Rutland",
"Sawyers Arms",
"Shirley East",
"Shirley West",
"Sockburn",
"Somerfield",
"South Richmond",
"Spreydon",
"St Albans East",
"St Albans West",
"St Martins",
"Strowan",
"Styx",
"Styx Mill",
"Sydenham",
"Templeton",
"Travis",
"Upper Riccarton",
"Waltham",
"Westburn",
"Westmorland",
"Wharenui",
"Wigram",
"Woolston South",
"Woolston West",
"Yaldhurst",
"Darfield",
"Lincoln",
"Leeston",
"Rolleston",
"Abbotsford",
"Andersons Bay",
"Aramoana",
"Balmacewen",
"Belleknowes",
"Brighton",
"Broad Bay-Portobello",
"Brockville",
"Bush Road ",
"Caledonian",
"Caversham",
"Concord",
"Corstorphine East",
"Corstorphine West",
"East Taieri",
"Fairfield",
"Forbury",
"Forrester Park",
"Fryatt",
"Glenleith",
"Green Island Central",
"Halfway Bush",
"Helensburgh",
"High St-Stuart St",
"High St-The Oval",
"Inner Peninsula",
"Kaikorai Hill",
"Kaikorai Lagoon",
"Kenmure",
"Macandrew Bay",
"Maori Hill",
"Mornington",
"Mosgiel East",
"Mosgiel South",
"Musselburgh",
"North Dunedin",
"North-East Valley",
"Opoho",
"Otago University",
"Port Chalmers",
"Ravensbourne",
"Raynbirds Bay",
"Roslyn North",
"Roslyn South",
"Sandymount",
"Sawyers Bay",
"South Dunedin",
"St Clair",
"St Kilda Central",
"St Kilda East",
"St Kilda West",
"St Leonards-Blanket Bay",
"Stuart St-Frederick St",
"Taiaroa-Cape Saunders",
"Vauxhall",
"Wakari",
"Waldronville",
"Wingatui",
"Woodhaugh",
"Wyllies Crossing",
"Alexandra",
"Cromwell"
]