
package nz.govt.msd.pst.messaging.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ClientService", targetNamespace = "http://msd.govt.nz/client", wsdlLocation = "file:/D:/code/pst/messaging/wsdl/ClientServiceContract.wsdl")
public class ClientService
    extends Service
{

    private final static URL CLIENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(nz.govt.msd.pst.messaging.client.ClientService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = nz.govt.msd.pst.messaging.client.ClientService.class.getResource("");
            url = new URL(baseUrl, "file:/D:/code/pst/messaging/wsdl/ClientServiceContract.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/code/pst/messaging/wsdl/ClientServiceContract.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CLIENTSERVICE_WSDL_LOCATION = url;
    }

    public ClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientService() {
        super(CLIENTSERVICE_WSDL_LOCATION, new QName("http://msd.govt.nz/client", "ClientService"));
    }

    /**
     * 
     * @return
     *     returns ClientServiceSoap
     */
    @WebEndpoint(name = "ClientServiceSoap")
    public ClientServiceSoap getClientServiceSoap() {
        return super.getPort(new QName("http://msd.govt.nz/client", "ClientServiceSoap"), ClientServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientServiceSoap
     */
    @WebEndpoint(name = "ClientServiceSoap")
    public ClientServiceSoap getClientServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://msd.govt.nz/client", "ClientServiceSoap"), ClientServiceSoap.class, features);
    }

}
