
package nz.govt.msd.pst.messaging.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClientServiceSoap", targetNamespace = "http://msd.govt.nz/client")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientServiceSoap {


    /**
     * This Webservice returns a list of client details based on a list passed in If a client is not found in the provided list, it will be silently not returned
     * 
     * @param minimalClientDetailsRequest
     * @return
     *     returns nz.govt.msd.pst.messaging.client.MinimalClientDetailsResponse
     */
    @WebMethod(action = "http://msd.govt.nz/client/minimalDetails")
    @WebResult(name = "minimalClientDetailsResponse", targetNamespace = "http://msd.govt.nz/client")
    @RequestWrapper(localName = "minimalDetails", targetNamespace = "http://msd.govt.nz/client", className = "nz.govt.msd.pst.messaging.client.MinimalDetails")
    @ResponseWrapper(localName = "minimalDetailsResponse", targetNamespace = "http://msd.govt.nz/client", className = "nz.govt.msd.pst.messaging.client.MinimalDetailsResponse")
    public MinimalClientDetailsResponse minimalDetails(
        @WebParam(name = "minimalClientDetailsRequest", targetNamespace = "http://msd.govt.nz/client")
        MinimalClientDetailsRequest minimalClientDetailsRequest);

    /**
     * 
     * @param createBasicNoteRequest
     */
    @WebMethod(action = "http://msd.govt.nz/client/createNote")
    @RequestWrapper(localName = "createNote", targetNamespace = "http://msd.govt.nz/client", className = "nz.govt.msd.pst.messaging.client.CreateNote")
    @ResponseWrapper(localName = "createNoteResponse", targetNamespace = "http://msd.govt.nz/client", className = "nz.govt.msd.pst.messaging.client.CreateNoteResponse")
    public void createNote(
        @WebParam(name = "createBasicNoteRequest", targetNamespace = "http://msd.govt.nz/client/notes")
        CreateBasicNoteRequest createBasicNoteRequest);

}
